<BlockScreen>
    header: header

    GridLayout:
        size: root.width, root.height
        cols: 1

        Header:
            id: header

        Nwboxlayout:
            size_hint_y: None
            height: dp(10)

        BoxLayout:
            size_hint_y: None
            height: dp(60)
            orientation: 'horizontal'

            Nwlabel:
                _text: 'Block Hash:'

            Nwlabel:
                _text: 'xxxxxxxxxxxxxxxxxxxxxxxxxxx'
